# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "625e22f5af8d7abd2613b43a44e21713"
application_url = "https://nights-our-focusing-subscribers.trycloudflare.com"
embedded = true
name = "subi-mida"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://nights-our-focusing-subscribers.trycloudflare.com/auth/callback",
  "https://nights-our-focusing-subscribers.trycloudflare.com/auth/shopify/callback"
]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
