# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae0a91e02b955afaa838c581b96136b2"
name = "subscription-pro"
application_url = "https://fin-broke-skills-earn.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_payment_methods,read_own_subscription_contracts,read_products,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://fin-broke-skills-earn.trycloudflare.com/auth/callback",
  "https://fin-broke-skills-earn.trycloudflare.com/auth/shopify/callback"
]

[app_proxy]
url = "https://fin-broke-skills-earn.trycloudflare.com/api/proxy"
subpath = "subscription-pro"
prefix = "apps"

[pos]
embedded = false
